algoritmo "semnome"
// Fun??o :
// Autor :
// Data : 19/03/2014
// Se??o de Declara??es
var
cont, soma:inteiro
idade:inteiro
inicio
cont <- 0
repita
      //contagem ate 5
   cont <- cont + 1
   //pergunte a idade
   escreva("digite uma idade:")
   leia(idade)
   //soma as idades
   soma <- soma + idade

ate (cont = 5)
//mostra a media das idades dividiondo a soma pelo cont
escreva("a media das idades é ", soma/cont)
fimalgoritmo
