algoritmo "semnome"
// Função :
// Autor :
// Data : 19/03/2014
// Seção de Declarações 
var
cont:inteiro
resposta: caracter
inicio
cont <- 0

enquanto cont < 5 faca

         escreva("deseja continuar, se sim digite: 's', se nao digite: 'n' ?")
         leia(resposta)
         
         se resposta = "n" entao
            interrompa
         fimse
         cont <- cont + 1
fimenquanto



fimalgoritmo
