algoritmo "semnome"
// Função :
// Autor :
// Data : 18/03/2014
// Seção de Declarações
var
numero:inteiro
inicio
// Seção de Comandos

escreva("informe um numero inteiro: ")
leia(numero)

se(numero > 10)entao
          escreval("esse numero é maior que 10")
senao se(numero < 10)  entao
          escreval("esse numero é menor que 10")
senao
          escreval("esse numero é igual que 10")
fimse
fimalgoritmo

